wandb_version: 1

batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 10
gloss_model_name:
  desc: null
  value: bert-base-cased
gradient_clipping:
  desc: null
  value: 2
loss:
  desc: null
  value: cross_entropy
lr:
  desc: null
  value: 0.0001
max_len:
  desc: null
  value: 128
sentence_model_name:
  desc: null
  value: bert-base-cased
weight_decay:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687443823.441358
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      3:
      - 1
      - 5
      - 7
      - 23
      4: 3.10.10
      5: 0.14.2
      6: 4.25.1
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
