wandb_version: 1

batch_size:
  value: 4
epochs:
  value: 10
gloss_model_name:
  value: roberta-base
gradient_clipping:
  value: 2
loss:
  value: cross_entropy
lr:
  value: 1.0e-07
max_len:
  value: 512
sentence_model_name:
  value: bert-base-cased
weight_decay:
  value: 0
