wandb_version: 1

batch_size:
  value: 16
epochs:
  value: 10
gloss_model_name:
  value: roberta-base
gradient_clipping:
  value: 0.5
loss:
  value: cross_entropy
lr:
  value: 2.0e-05
max_len:
  value: 128
sentence_model_name:
  value: roberta-base
weight_decay:
  value: 5.0e-05
