wandb_version: 1

batch_size:
  value: 16
epochs:
  value: 10
gloss_model_name:
  value: bert-base-cased
gradient_clipping:
  value: 0.5
loss:
  value: cross_entropy
lr:
  value: 3.0e-05
max_len:
  value: 128
sentence_model_name:
  value: bert-base-cased
weight_decay:
  value: 1.0e-05
