wandb_version: 1

batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 4
gloss_model_name:
  desc: null
  value: bert-base-cased
gradient_clipping:
  desc: null
  value: 0.5
learning_rate:
  desc: null
  value: 3.0e-05
loss:
  desc: null
  value: cross_entropy
max_len:
  desc: null
  value: 512
sentence_model_name:
  desc: null
  value: bert-base-cased
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687173243.916157
    t:
      1:
      - 1
      - 9
      - 11
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 49
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.16
      5: 0.15.4
      6: 4.30.2
      8:
      - 5
